title: "Dianashiba"
description: "Personal Homepage"

remote_theme: ankitsultana/researcher

nav:
  - name: "About"
    link: "/"

footer: "&copy; 2026 Dianashiba"

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-remote-theme
