title: "Dianashiba"
url: "https://dianashiba.github.io/"
baseurl: ""

markdown: kramdown

footer: yes
footer_text: "Dianashiba©2026"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""

remote_theme: ankitsultana/researcher@gem
plugins:
  - jekyll-remote-theme
